# Dependabot version updates
# https://docs.github.com/code-security/dependabot/dependabot-version-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 10
    groups:
      dependencies:
        patterns:
          - "*"
